# Config file for [Air](https://github.com/air-verse/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
# Add additional arguments when running binary (bin/full_bin).
args_bin = []
# Binary file yields from `cmd`.
bin = "./tmp/workoutapp"
# Just plain old shell command. You could use `make` as well.
cmd = "make build"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000
exclude_dir = [
  "tmp",
  "testdata",
  "scripts",
  "node_modules",
  "internal/sqlc/workoutdb",
]
# Exclude files.
exclude_file = ["web/static/css/output.css"]
# Exclude specific regular expressions.
exclude_regex = ["_test.go", "_templ.go"]
# Exclude unchanged files.
exclude_unchanged = false
# Follow symlink for directories
follow_symlink = false
# Customize binary, can setup environment variables when run your app.
full_bin = ""
# Watch these directories if you specified.
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "css", "sql"]
# Watch these files.
include_file = []
# Delay after sending Interrupt signal
kill_delay = "60s"
# This log file places in your tmp_dir.
log = "build-errors.log"
# Poll files for changes instead of using fsnotify.
poll = false
# Poll interval (defaults to the minimum interval of 500ms).
poll_interval = 0
# Array of commands to run after ^C
post_cmd = []
# Array of commands to run before each build
pre_cmd = []
# Rerun binary or not
rerun = false
# Delay after each execution
rerun_delay = 500
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
# Stop running old binary when build errors occur.
stop_on_error = true

[color]
# Customize each part's color. If no color found, use the raw app log.
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
# Only show main log (silences watcher, build, runner)
main_only = false
# Show log time
time = false
# silence all logs produced by air 
silent = false

[misc]
# Delete tmp directory on exit
clean_on_exit = false

[proxy]
# Enable live-reloading on the browser.
enabled = true
app_port = 8080
proxy_port = 8081

[screen]
clear_on_rebuild = false
keep_scroll = true
