-- Inserts a single record of progress.
-- name: InsertProgress :one
INSERT INTO progress (lift, date, weight, sets, reps, side_weight)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING *;

-- Lists all progress for a given date.
-- name: ListProgressForDay :many
SELECT * FROM progress
WHERE date = ?;

-- Deletes the progress matching the ID.
-- name: DeleteProgress :exec
DELETE FROM progress
WHERE id = ?;

-- Gets the latest progress for the lift.
-- name: GetLatestProgressForLift :one
SELECT sqlc.embed(progress), sqlc.embed(side_weight)
FROM progress
JOIN side_weight
    ON (COALESCE(progress.side_weight, 'x1') = side_weight.id)
WHERE progress.lift = ?
ORDER BY progress.id DESC
LIMIT 1;

-- Gets the lift matching the ID.
-- name: GetLift :one
SELECT * FROM lift
WHERE id = ?
LIMIT 1;

-- name: ListRoutinesForDate :many
SELECT routine.*
FROM schedule
INNER JOIN routine_workout_mapping
    ON schedule.workout = routine_workout_mapping.workout
INNER JOIN routine
    ON (routine_workout_mapping.routine = routine.id)
WHERE schedule.date = ?;

-- name: ListAllIndividualLifts :many
SELECT id
FROM lift;

-- name: ListAllIndividualSideWeights :many
SELECT id
FROM side_weight;

-- name: ListAllIndividualMuscles :many
SELECT id
FROM muscle;

-- name: ListAllIndividualMovements :many
SELECT id
FROM movement;

-- name: ListAllIndividualRoutines :many
SELECT id
FROM routine;

-- name: ListAllIndividualLiftGroups :many
SELECT id
FROM lift_group;

-- name: ListCurrentSchedule :many
SELECT *
FROM schedule
WHERE date >= ?
ORDER BY date ASC;

-- name: GetSchedule :one
SELECT * FROM schedule
WHERE date = ?;

-- name: ListAllIndividualWorkouts :many
SELECT id FROM workout;

-- name: UpdateSchedule :one
UPDATE schedule
SET workout = ?, notes = ?
WHERE date = ?
RETURNING *;

-- name: GetLatestScheduleDate :one
SELECT date
FROM schedule
ORDER BY date DESC
LIMIT 1;

-- name: InsertSchedule :one
INSERT INTO schedule (date, workout, notes)
VALUES (?, ?, ?)
RETURNING *;

-- name: DeleteScheduleAfterAndIncludingDate :exec
DELETE FROM schedule
WHERE date >= ?;

-- name: DeleteSchedule :exec
DELETE FROM schedule
WHERE date = ?;

-- name: UpdateScheduleDate :one
UPDATE schedule
SET date = @to_date
WHERE date = @from_date
RETURNING *;

-- name: ListAllIndividualScheduleLists :many
SELECT DISTINCT id
FROM schedule_list;

-- name: ListWorkoutsForScheduleList :many
SELECT workout
FROM schedule_list
WHERE id = ?
ORDER BY day ASC;

-- name: ListMostRecentProgressForLift :many
SELECT *
FROM progress
WHERE lift = ?
ORDER BY id DESC
LIMIT ?;

-- name: GetWorkoutForDate :one
SELECT workout
FROM schedule
WHERE date = ?
LIMIT 1;

-- name: QueryLiftGroupsForDate :many
SELECT
    lift.lift_group,
    SUM(progress.reps * progress.sets) AS total_reps
FROM
    progress
INNER JOIN
    lift ON (progress.lift = lift.id)
WHERE progress."date" = ?
GROUP BY lift.lift_group;

-----------------------
-- sqlfluff settings --
-----------------------

-- Treat as sqlite.
-- sqlfluff:dialect:sqlite

-- Disable unknown column count rule. The structs generated by `*`
-- are better and are handled gracefully by sqlc.
-- sqlfluff:exclude_rules:L044
