name: "Test"
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build devShell
        run: nix build --no-link .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default
      - name: "Run make gha"
        shell: 'nix develop -c bash -e {0}'
        run: make gha
